const fs = require('fs');

let fileStr = fs.readFileSync('app/twa/page.tsx', 'utf8');

fileStr = fileStr.replace(
  'const basePlans = [\n  { id: "base", title: "Старт", desc: "Базовая лидогенерация", price: 21000, features: ["Многоуровневое меню навигации", "Умная форма заявки", "Система мгновенных алертов", "Базовый пульт управления"] },\n  { id: "business", title: "Бизнес", desc: "Автономный отдел продаж", price: 45000, features: ["Интерактивный каталог", "Модуль корзины и чекаута", "Прямой биллинг (Оплата онлайн)", "Система записи (Букинг)", "Экспорт данных"] },\n  { id: "scale", title: "Масштаб", desc: "Премиальная TWA-экосистема", price: 120000, features: ["Полноценный Web-интерфейс (TWA)", "Продвинутый Личный Кабинет", "Сложные фильтры", "Бесшовная интеграция с CRM"] },\n];',
  'const basePlans = [\n  { id: "base", title: "Старт", desc: "Только Landing (Свирепая конверсия)", price: 90000, features: ["Многоуровневое меню навигации", "Умная форма заявки", "Система мгновенных алертов", "Базовый пульт управления"] },\n  { id: "business", title: "Бизнес", desc: "Telegram Web App (Внутри экосистемы)", price: 150000, features: ["Интерактивный каталог", "Модуль корзины и чекаута", "Прямой биллинг (Оплата онлайн)", "Система записи (Букинг)", "Экспорт данных"] },\n  { id: "scale", title: "Доминация", desc: "Full-Stack доминация (Landing + TWA + Bot)", price: 290000, features: ["Полноценный Web-интерфейс (TWA)", "Продвинутый Личный Кабинет", "Сложные фильтры", "Бесшовная интеграция с CRM"] },\n];'
);

fileStr = fileStr.replace(
  'const modules = [\n  { id: "crm", title: "Интеграция с amoCRM / Битрикс24", price: 15000 },\n  { id: "ai", title: "Интеграция ИИ (ChatGPT-ассистент)", price: 20000 },\n  { id: "payment", title: "Подключение онлайн-кассы / Крипты", price: 10000 },\n  { id: "admin", title: "Продвинутая Админ-панель", price: 25000 },\n  { id: "video", title: "Видео-аватар на входе", price: 12000 },\n  { id: "referral", title: "Реферальная система", price: 18000 },\n  { id: "analytics", title: "Сквозная аналитика", price: 22000 },\n  { id: "push", title: "Push-уведомления (Массовые рассылки)", price: 8000 },\n  { id: "i18n", title: "Мультиязычность (i18n)", price: 15000 },\n  { id: "deploy", title: "Развертывание на сервере клиента", price: 8000 },\n];',
  'const modules = [\n  { id: "crm", title: "Интеграция с amoCRM / Битрикс24", price: 40000 },\n  { id: "ai", title: "Интеграция ИИ (Автономный продавец)", price: 80000 },\n  { id: "payment", title: "Подключение онлайн-кассы / Крипты", price: 30000 },\n  { id: "admin", title: "Продвинутая Админ-панель", price: 60000 },\n  { id: "video", title: "3D Motion, GSAP, Cyberpunk эффекты", price: 50000 },\n  { id: "referral", title: "Реферальная система", price: 40000 },\n  { id: "analytics", title: "Сквозная аналитика", price: 45000 },\n  { id: "push", title: "Push-уведомления (Массовые рассылки)", price: 20000 },\n  { id: "i18n", title: "Мультиязычность (i18n)", price: 35000 },\n  { id: "deploy", title: "Развертывание на сервере клиента", price: 25000 },\n];'
);

fs.writeFileSync('app/twa/page.tsx', fileStr);
